### ISSUE TITLE
CORS error in Chrome

### ISSUE THREAD

**Issue by borysyuk** [openspending/babbage.ui#28]
http://cosmopolitan.openspending.org/v1/polygons/country:MD?format=json. The 'Access-Control-Allow-Origin' header has a value 'http://localhost:63342' that is not equal to the supplied origin. Origin 'http://os-viewer.herokuapp.com' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by akariv** [comment]
if this only happens with the debugger active, you might work around this issue by running chrome with the `--disable-web-security --user-data-dir` flags.

**Comment by pwalsh** [comment]
WONTFIX
