### ISSUE TITLE
filter by key but present label

### ISSUE THREAD

**Issue by jbothma** [openspending/babbage.ui#35]
Why does it filter by the label of a dimension when the key_attribute is defined? I would have figured that the idea is to present the label to the user but use the associated key to do the filter.

**Comment by akariv** [comment]
Hey, I think this is similar to this issue:

https://github.com/openspending/openspending/issues/930

**Comment by jbothma** [comment]
Yes - it sounds like that's describing the opposite - that the label is not being used for presentation when it could, while this is about the key not being used when it should (should because who says labels must be unique for a given non-key attribute)

**Comment by akariv** [comment]
Well, the reason for both issues is the same (as well as the solution for both...)
