### ISSUE TITLE
Implement bar charts and line charts

### ISSUE THREAD

**Issue by pudo** [openspending/babbage.ui#4]
I would propose to use angular-nvd3 for that purpose, so that we don't have to re-invent the wheel wrt. axis labelling and stuff like that.

**Comment by milafrerichs** [comment]
I started using vega-lite.  :)
And it was not that complicated. 
I think reusing an angular module does not work that well with the way angular-cubes is set up. You would have to write your own directive anyway. 
Or what do you think? Should I create a WIP PR for the barchart so you can check it out?

**Comment by pudo** [comment]
I'm largely agnostic wrt. Vega vs. NVD3. Like the idea of skipping the wrappers since we do have to create our own directives. Very excited about the PR!
